### PR TITLE
Added options to hide menu bar icon (config key and menu item)

### PR DESCRIPTION
**Pull request by jpsim**
Addresses #77.

### CODE REVIEW

**Comment by jpsim** [comment]
Hi @jigish, could you please take a look at this to see if it's merge-worthy? Thanks!

**Comment by hector** [comment]
Come on @jigish, this is a great feature! :)

**Comment by mattr-** [comment]
I'll take a look at this later today. If it's merge worthy, it'll go into mattr-/slate and I'll link it here so that people know.

**Comment by mattr-** [comment]
@jpsim What did you remove out of `MainMenu.xib`?

**Comment by jpsim** [comment]
That's a great question! I made this PR over a year ago, so I don't remember. I'll have to download and diff locally.

**Comment by jpsim** [comment]
@mattr- it turns out that I didn't make any changes to the xib _myself_, but Xcode just updated it to a newer format, simply by opening it. Yay Xcode!

I've reset the xib to its previous state.

**Comment by mattr-** [comment]
This has been merged to mattr-/slate@65000ac382

**Comment by jpsim** [comment]
image

**Pull request closed without merging**
