### PR TITLE
Iconography

### PR DESCRIPTION
**Pull request by maxvoltar**
New app icon and status icon.

dribbble-800x600

@niw has a screenshot of the icons in use: https://twitter.com/niw/status/801237742105464832

### CODE REVIEW

**Comment by mdznr** [comment]
👍 These are much improved!

Could the blue color used in statusActive.pdf be a bit darker to provide a little bit more contrast?

**Comment by maxvoltar** [comment]
It needs to work with both the light (default) chrome and dark chrome, but tweaking it doesn't take long.

**Comment by mdznr** [comment]
I think the color used for selection/highlighting in the menu bar (`[NSColor selectedMenuItemColor]`, which roughly equates to #187AEE) is probably best. This color could be burned into the image, but should likely be done programmatically to ensure that it gets the proper treatment when high contrast mode is enabled (System Preferences > Accessibility > Display > Increase Contrast).

Additionally, to provide more visual contrast against the normal state, I made the normal state outlined, and the active state filled. I feel the outlined style also fits in better with the other status item icons.
[status.pdf](https://github.com/jigish/slate/files/609693/status.pdf)
[statusActive.pdf](https://github.com/jigish/slate/files/609694/statusActive.pdf)

**Comment by maxvoltar** [comment]
Thanks @mdznr, changed the color of the active state!

Typically, status bar icons don't change visually between active and default state, they just get a different color treatment, so I didn't make that change.

**Comment by niw** [comment]
Updated graphics and screenshots.
black
white

**Pull request closed without merging**
