### PR TITLE
Work on wider support for detecting display configuration changes

### PR DESCRIPTION
**Pull request by cmsj**
This is more of a notification than a pull request - I think this Quartz method may provide a more stable and supportable way of updating the layouts when displays are added or removed, but right now it is added on top of your existing detection method.

Assuming the Quartz way is acceptable, I would suggest we remove the existing method entirely and rely fully on Quartz. I would note, however, that I only have Mountain Lion systems to test on, so if this API is unsuitable in earlier versions, some combination will be required!

### CODE REVIEW

**Comment by jigish** [comment]
thanks for looking at this. i've been busy as of late and have needed to fix this for mountain lion for a while. i'll test this on Lion to see how it works and potentially merge this and remove the other code.

**Comment by arturhoo** [comment]
Any chances of this being accepted? I'm on ML 10.8.2 and monitor changes are not detected.

**Comment by jigish** [comment]
yah, I'll accept this and publish a new version sometime this weekend. just came back from a long vacation so I'm a bit spent right now.

**Comment by jigish** [comment]
finally merged. testing now then pushing a new version.

**Pull request merged**
