### PR TITLE
The only Pull Request that should be merged!

### PR DESCRIPTION
**Pull request by mastercyb**
Abundance notice!

### CODE REVIEW

**Comment by kenliu** [comment]
+1

**Comment by nylen** [comment]
:+1:, ping @jigish

**Comment by KurtPreston** [comment]
+1

**Comment by nylen** [comment]
-1, slate sucks

**Comment by durdn** [comment]
+1

**Comment by azer** [comment]
+1

**Comment by mrooney** [comment]
+1 @jigish :)

**Comment by sinofool** [comment]
+1

**Comment by mrooney** [comment]
@jigish any chance of a merge of this super simple documentation PR? I think it would really help others still get benefit from your hard work!

**Comment by donjohnson** [comment]
If nothing else, @21xhipster could re-title the PR with "Let's migrate, everybody!" or something similar. An issue with the same title might help too.

**Comment by kevin-chau** [comment]
+1

**Pull request closed without merging**
